### ISSUE TITLE
Cannot use normalize scroll

### ISSUE THREAD

**Issue by samuelreichor** [hypernym-studio/nuxt-gsap#61]
### Steps to Reproduce

1. `const { $ScrollTrigger } = useNuxtApp();`
2. try to use it ` $ScrollTrigger.normalizeScroll(true); `

### Current Behavior

I get this error when I try to use the [normalizescroll](https://gsap.com/docs/v3/Plugins/ScrollTrigger/static.normalizeScroll()/) from gsap. Am i doing something wrong?

![image](https://github.com/user-attachments/assets/ef84687c-ce42-454c-8847-33d242390ce5)

### Expected Behavior

Normalize scroll should work as expected. 

### Version

2.4.2

**Comment by ivodolenc** [comment]
Hi, this is most likely due to the `client-side` plugins being loaded on the `server`.

Try to wrap the code in the `onMounted()` hook, it should work fine.

```html
<script setup lang="ts">
  const { $ScrollTrigger } = useNuxtApp()

  onMounted(() => {
    $ScrollTrigger.normalizeScroll(true) // 👈🏻
  })
</script>
```

Also, examples are in the [docs](https://github.com/hypernym-studio/nuxt-gsap?tab=readme-ov-file#module) and [playground](https://github.com/hypernym-studio/nuxt-gsap/blob/main/playground/pages/index.vue).

I just tested the module with the given example and everything works as expected so I'm closing it as resolved.

If you find any problem, feel free to reopen it 👍🏻
